name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Adjust branch name if necessary

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker buildx create --use
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker buildx build --platform linux/amd64 -t $DOCKER_USERNAME/slr:latest --push .

      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
             sudo -i << 'EOF'
             container_id=$(docker ps -aqf "name=slr")
              if [ ! -z "$container_id" ]; then
                docker stop "$container_id" || true
                docker rm "$container_id" || true
              fi
              docker pull salar202/slr:latest
              docker run -d -p 8080:8080 --name slr salar202/slr:latest
              EOF
